import type { GodotToolDefinition } from './types.js';

export const VISUAL_TOOL_DEFINITIONS: GodotToolDefinition[] = [
  {
    name: 'animation',
    description: 'Create, inspect, remove, and edit AnimationPlayer tracks and keyframes',
    inputSchema: {
      type: 'object',
      properties: {
        projectPath: { type: 'string', description: 'Path to the Godot project directory' },
        scenePath: { type: 'string', description: 'Project-relative scene path' },
        action: {
          type: 'string',
          enum: ['list', 'create', 'add_track', 'set_keyframe', 'get_info', 'remove'],
          description: 'Animation action. Defaults to list.',
        },
        nodePath: { type: 'string', description: 'Parent node path for create action' },
        animationPlayerPath: { type: 'string', description: 'AnimationPlayer node path for editing existing animations' },
        playerName: { type: 'string', description: 'AnimationPlayer node name. Defaults to AnimationPlayer.' },
        animationName: { type: 'string', description: 'Animation name. Defaults to default.' },
        length: { type: 'number', description: 'Animation length in seconds. Defaults to 1.0.' },
        trackType: { type: 'string', enum: ['value', 'method', 'bezier'], description: 'Track type for add_track. Defaults to value.' },
        trackPath: { type: 'string', description: 'Animation track path, such as Sprite2D:modulate or .:position' },
        trackIndex: { type: 'number', description: 'Existing track index for keyframe insertion' },
        time: { type: 'number', description: 'Keyframe time in seconds' },
        value: { description: 'Keyframe value, using structured Variant values where needed' },
        updateMode: { type: 'string', enum: ['continuous', 'discrete', 'capture'], description: 'Value track update mode' },
        tracks: {
          type: 'array',
          description: 'Optional value tracks with path and keyframes, e.g. [{ path: "Player:position", keyframes: [{ time: 0, value: { type: "Vector2", value: [0, 0] } }] }]',
          items: {
            type: 'object',
            properties: {
              path: { type: 'string' },
              keyframes: {
                type: 'array',
                items: {
                  type: 'object',
                  properties: {
                    time: { type: 'number' },
                    value: {},
                  },
                  required: ['time', 'value'],
                },
              },
            },
            required: ['path', 'keyframes'],
          },
        },
      },
      required: ['projectPath', 'scenePath'],
    },
  },
  {
    name: 'animation_state_machine',
    description: 'Create, inspect, and configure AnimationTree state machines',
    inputSchema: {
      type: 'object',
      properties: {
        projectPath: { type: 'string', description: 'Path to the Godot project directory' },
        scenePath: { type: 'string', description: 'Project-relative scene path' },
        action: { type: 'string', enum: ['list', 'create', 'set_transition_parameters'], description: 'State machine action. Defaults to list.' },
        nodePath: { type: 'string', description: 'Parent node path for create action' },
        treePath: { type: 'string', description: 'Existing AnimationTree node path for transition updates' },
        treeName: { type: 'string', description: 'AnimationTree node name. Defaults to AnimationTree.' },
        animationPlayerPath: { type: 'string', description: 'Optional AnimationPlayer node path used by the AnimationTree.' },
        states: {
          type: 'array',
          description: 'Optional state definitions, e.g. [{ name: "idle", animationName: "idle" }].',
          items: {
            type: 'object',
            properties: {
              name: { type: 'string' },
              animationName: { type: 'string' },
              position: { type: 'object' },
            },
            required: ['name'],
          },
        },
        transitions: {
          type: 'array',
          description: 'Optional transitions, e.g. [{ from: "idle", to: "run" }].',
          items: {
            type: 'object',
            properties: {
              from: { type: 'string' },
              to: { type: 'string' },
              parameters: { type: 'object' },
            },
            required: ['from', 'to'],
          },
        },
        fromState: { type: 'string', description: 'Transition source state for set_transition_parameters' },
        toState: { type: 'string', description: 'Transition target state for set_transition_parameters' },
        transitionIndex: { type: 'number', description: 'Transition index for set_transition_parameters' },
        transitionParameters: {
          type: 'object',
          description: 'AnimationNodeStateMachineTransition properties such as xfade_time, advance_mode, switch_mode, advance_condition, priority, and reset.',
        },
      },
      required: ['projectPath', 'scenePath'],
    },
  },
  {
    name: 'signal',
    description: 'List, connect, or disconnect node signals in a scene',
    inputSchema: {
      type: 'object',
      properties: {
        projectPath: { type: 'string', description: 'Path to the Godot project directory' },
        scenePath: { type: 'string', description: 'Project-relative scene path' },
        action: { type: 'string', enum: ['list', 'connect', 'disconnect'], description: 'Signal action. Defaults to list.' },
        nodePath: { type: 'string', description: 'Source node path' },
        signalName: { type: 'string', description: 'Signal name for connect/disconnect' },
        targetNodePath: { type: 'string', description: 'Target node path for connect/disconnect' },
        methodName: { type: 'string', description: 'Target method name for connect/disconnect' },
      },
      required: ['projectPath', 'scenePath', 'nodePath'],
    },
  },
  {
    name: 'group',
    description: 'List, add, or remove node groups',
    inputSchema: {
      type: 'object',
      properties: {
        projectPath: { type: 'string', description: 'Path to the Godot project directory' },
        scenePath: { type: 'string', description: 'Project-relative scene path' },
        action: { type: 'string', enum: ['list', 'add', 'remove'], description: 'Group action. Defaults to list.' },
        nodePath: { type: 'string', description: 'Node path' },
        groupName: { type: 'string', description: 'Group name for add/remove' },
      },
      required: ['projectPath', 'scenePath', 'nodePath'],
    },
  },
  {
    name: 'ui',
    description: 'Create Control nodes, reusable UI templates, themes, and automatic signal wiring',
    inputSchema: {
      type: 'object',
      properties: {
        projectPath: { type: 'string', description: 'Path to the Godot project directory' },
        scenePath: { type: 'string', description: 'Project-relative scene path' },
        action: {
          type: 'string',
          enum: ['create', 'create_theme', 'apply_theme', 'create_template', 'auto_connect_signals'],
          description: 'UI action. Defaults to create.',
        },
        parentNodePath: { type: 'string', description: 'Parent node path. Defaults to root.' },
        nodePath: { type: 'string', description: 'Existing Control node path for theme application or signal scanning' },
        nodeType: { type: 'string', description: 'Control node type, such as Control, Label, Button, or PanelContainer.' },
        nodeName: { type: 'string', description: 'Name for the new UI node' },
        text: { type: 'string', description: 'Optional text for Label/Button-like nodes' },
        themePath: { type: 'string', description: 'Project-relative Theme .tres/.res path for create_theme/apply_theme' },
        templateName: { type: 'string', enum: ['hud_bar', 'menu_panel', 'dialog_box'], description: 'Reusable Control tree template for create_template' },
        targetNodePath: { type: 'string', description: 'Signal receiver node path for auto_connect_signals' },
        signalMappings: { type: 'array', items: { type: 'object' }, description: 'Optional signal mappings: [{ nodePath, signalName, methodName }]' },
        colors: { type: 'object', description: 'Theme colors keyed by Type/name, such as {"Label/font_color": Color}' },
        constants: { type: 'object', description: 'Theme constants keyed by Type/name' },
        fontSizes: { type: 'object', description: 'Theme font sizes keyed by Type/name' },
        styleboxes: { type: 'object', description: 'Theme StyleBoxFlat entries keyed by Type/name' },
        layoutPreset: {
          type: 'string',
          enum: ['full_rect', 'center', 'top_left'],
          description: 'Optional Control layout preset.',
        },
        properties: { type: 'object', description: 'Optional node properties' },
      },
      required: ['projectPath', 'scenePath', 'nodeType', 'nodeName'],
    },
  },
  {
    name: 'material',
    description: 'Create, read, update, and apply Godot material resources',
    inputSchema: {
      type: 'object',
      properties: {
        projectPath: { type: 'string', description: 'Path to the Godot project directory' },
        action: {
          type: 'string',
          enum: ['create', 'read', 'update', 'apply', 'list_templates', 'create_from_template'],
          description: 'Material action. Defaults to read.',
        },
        resourcePath: { type: 'string', description: 'Project-relative material resource path for create/read/update' },
        materialPath: { type: 'string', description: 'Project-relative material resource path for apply' },
        materialType: {
          type: 'string',
          enum: ['StandardMaterial3D', 'CanvasItemMaterial', 'ShaderMaterial'],
          description: 'Material type for create. Defaults to StandardMaterial3D.',
        },
        shaderPath: { type: 'string', description: 'Project-relative .gdshader path when creating ShaderMaterial' },
        presetName: { type: 'string', enum: ['unlit', 'lit', 'emissive', 'transparent'], description: 'Optional material preset applied before custom properties' },
        templateName: {
          type: 'string',
          enum: ['block_unlit', 'emissive_pickup', 'transparent_ghost', 'ui_canvas'],
          description: 'Reusable material template for create_from_template.',
        },
        properties: { type: 'object', description: 'Material properties to set, using structured Variant values where needed' },
        scenePath: { type: 'string', description: 'Project-relative scene path for apply' },
        nodePath: { type: 'string', description: 'Target node path for apply' },
        propertyName: { type: 'string', description: 'Node material property to set. Defaults to material_override.' },
      },
      required: ['projectPath'],
    },
  },
  {
    name: 'shader',
    description: 'Create, read, inspect, and configure ShaderMaterial parameters',
    inputSchema: {
      type: 'object',
      properties: {
        projectPath: { type: 'string', description: 'Path to the Godot project directory' },
        action: {
          type: 'string',
          enum: ['create', 'read', 'inspect', 'set_parameters'],
          description: 'Shader action. Defaults to read.',
        },
        shaderPath: { type: 'string', description: 'Project-relative .gdshader path' },
        materialPath: { type: 'string', description: 'Project-relative ShaderMaterial resource path for set_parameters' },
        shaderType: { type: 'string', enum: ['canvas_item', 'spatial', 'particles'], description: 'Shader type for generated shader code' },
        code: { type: 'string', description: 'Full shader code for create' },
        includePaths: { type: 'array', items: { type: 'string' }, description: 'Known shader include paths to report alongside parsed #include directives' },
        textureDefaults: { type: 'object', description: 'Texture defaults keyed by sampler uniform name for generated ShaderMaterial setup' },
        parameters: { type: 'object', description: 'Shader parameter values for set_parameters' },
      },
      required: ['projectPath'],
    },
  },
  {
    name: 'lighting',
    description: 'Create and list basic Godot light and environment nodes',
    inputSchema: {
      type: 'object',
      properties: {
        projectPath: { type: 'string', description: 'Path to the Godot project directory' },
        scenePath: { type: 'string', description: 'Project-relative scene path' },
        action: { type: 'string', enum: ['create', 'list'], description: 'Lighting action. Defaults to list.' },
        parentNodePath: { type: 'string', description: 'Parent node path for create. Defaults to root.' },
        nodeType: {
          type: 'string',
          enum: ['DirectionalLight3D', 'PointLight3D', 'SpotLight3D', 'WorldEnvironment', 'PointLight2D', 'DirectionalLight2D'],
          description: 'Light/environment node type for create.',
        },
        nodeName: { type: 'string', description: 'Name for the new light/environment node' },
        properties: { type: 'object', description: 'Node properties to set, using structured Variant values where needed' },
      },
      required: ['projectPath', 'scenePath'],
    },
  },
  {
    name: 'particle',
    description: 'Create and list basic Godot particle emitter nodes',
    inputSchema: {
      type: 'object',
      properties: {
        projectPath: { type: 'string', description: 'Path to the Godot project directory' },
        scenePath: { type: 'string', description: 'Project-relative scene path' },
        action: { type: 'string', enum: ['create', 'list'], description: 'Particle action. Defaults to list.' },
        parentNodePath: { type: 'string', description: 'Parent node path for create. Defaults to root.' },
        nodeType: {
          type: 'string',
          enum: ['GPUParticles2D', 'GPUParticles3D', 'CPUParticles2D', 'CPUParticles3D'],
          description: 'Particle node type for create. Defaults to GPUParticles2D.',
        },
        nodeName: { type: 'string', description: 'Name for the new particle node' },
        processMaterialType: {
          type: 'string',
          enum: ['ParticleProcessMaterial'],
          description: 'Optional process material type for GPU particle nodes.',
        },
        amount: { type: 'number', description: 'Particle amount' },
        lifetime: { type: 'number', description: 'Particle lifetime in seconds' },
        emitting: { type: 'boolean', description: 'Whether particles emit immediately' },
        properties: { type: 'object', description: 'Additional node properties' },
      },
      required: ['projectPath', 'scenePath'],
    },
  },
  {
    name: 'tilemap',
    description: 'Create, list, and edit TileMapLayer or legacy TileMap nodes',
    inputSchema: {
      type: 'object',
      properties: {
        projectPath: { type: 'string', description: 'Path to the Godot project directory' },
        scenePath: { type: 'string', description: 'Project-relative scene path' },
        action: {
          type: 'string',
          enum: [
            'create',
            'list',
            'create_tileset',
            'add_atlas_source',
            'set_tile_metadata',
            'set_tile_collision',
            'set_tile_navigation',
            'set_terrain',
            'set_cell',
            'batch_set_cells',
            'fill_rect',
            'paint_random',
            'apply_template',
          ],
          description: 'TileMap or TileSet action. Defaults to list.',
        },
        parentNodePath: { type: 'string', description: 'Parent node path for create. Defaults to root.' },
        nodePath: { type: 'string', description: 'TileMapLayer or TileMap node path for painting actions' },
        nodeType: { type: 'string', enum: ['TileMapLayer', 'TileMap'], description: 'Tile map node type. Defaults to TileMapLayer on Godot versions that support it.' },
        nodeName: { type: 'string', description: 'Name for the new tile map node' },
        tileSetPath: { type: 'string', description: 'Optional project-relative TileSet .tres/.res path to assign' },
        texturePath: { type: 'string', description: 'Project-relative texture path for add_atlas_source' },
        atlasSourceId: { type: 'number', description: 'TileSet atlas source id for TileSet actions' },
        tileSize: { type: 'object', description: 'Atlas tile size, for example { "width": 16, "height": 16 } or a Vector2i value' },
        margin: { type: 'object', description: 'Atlas source margin as Vector2i-like value' },
        separation: { type: 'object', description: 'Atlas source separation as Vector2i-like value' },
        tiles: { type: 'array', items: { type: 'object' }, description: 'Tile definitions for atlas source creation or painting templates' },
        cell: { type: 'object', description: 'Cell coordinates for set_cell, e.g. { "type": "Vector2", "value": [0, 0] }' },
        sourceId: { type: 'number', description: 'Tile source id for set_cell. Defaults to -1, which erases the cell.' },
        atlasCoords: { type: 'object', description: 'Atlas coords for set_cell. Defaults to Vector2i(-1, -1).' },
        alternativeTile: { type: 'number', description: 'Alternative tile id for set_cell. Defaults to 0.' },
        cells: { type: 'array', items: { type: 'object' }, description: 'Cells for batch_set_cells. Each item supports cell, source_id, atlas_coords, alternative_tile.' },
        rect: { type: 'object', description: 'Rectangle for fill_rect: { "x":0, "y":0, "width":10, "height":10 }' },
        metadata: { type: 'object', description: 'Custom tile metadata for set_tile_metadata' },
        customDataLayers: { type: 'array', items: { type: 'object' }, description: 'TileSet custom data layer definitions with name and type' },
        physicsLayer: { type: 'number', description: 'TileSet physics layer index for collision data. Defaults to 0.' },
        navigationLayer: { type: 'number', description: 'TileSet navigation layer index for navigation data. Defaults to 0.' },
        terrainSet: { type: 'number', description: 'Terrain set index. Defaults to 0.' },
        terrain: { type: 'number', description: 'Terrain index inside the terrain set. Defaults to 0.' },
        terrainName: { type: 'string', description: 'Optional terrain name when configuring terrain data' },
        polygons: { type: 'array', items: { type: 'array' }, description: 'Collision or navigation polygons as arrays of points' },
        terrainBits: { type: 'object', description: 'Terrain peering bits keyed by Godot terrain bit integer' },
        weightedTiles: { type: 'array', items: { type: 'object' }, description: 'Weighted tile choices for randomized painting' },
        seed: { type: 'number', description: 'Deterministic seed for randomized map painting' },
        templateName: { type: 'string', enum: ['survivor_arena', 'room_grid'], description: 'Reusable map template name for apply_template' },
        tilePalette: { type: 'object', description: 'Named tile choices for templates, such as floor, wall, and obstacle' },
        properties: { type: 'object', description: 'Additional node properties' },
      },
      required: ['projectPath', 'scenePath'],
    },
  },
  {
    name: 'geometry',
    description: 'Create and list basic 2D geometry/debug drawing nodes',
    inputSchema: {
      type: 'object',
      properties: {
        projectPath: { type: 'string', description: 'Path to the Godot project directory' },
        scenePath: { type: 'string', description: 'Project-relative scene path' },
        action: { type: 'string', enum: ['create', 'list'], description: 'Geometry action. Defaults to list.' },
        parentNodePath: { type: 'string', description: 'Parent node path for create. Defaults to root.' },
        nodeType: { type: 'string', enum: ['Polygon2D', 'Line2D', 'Marker2D'], description: 'Geometry node type. Defaults to Polygon2D.' },
        nodeName: { type: 'string', description: 'Name for the new geometry node' },
        properties: { type: 'object', description: 'Node properties, such as polygon, points, width, color, or position' },
      },
      required: ['projectPath', 'scenePath'],
    },
  },
  {
    name: 'physics',
    description: 'Create and list physics bodies, areas, and collision shapes',
    inputSchema: {
      type: 'object',
      properties: {
        projectPath: { type: 'string', description: 'Path to the Godot project directory' },
        scenePath: { type: 'string', description: 'Project-relative scene path' },
        action: { type: 'string', enum: ['create', 'list'], description: 'Physics action. Defaults to list.' },
        parentNodePath: { type: 'string', description: 'Parent node path for create. Defaults to root.' },
        nodeType: {
          type: 'string',
          enum: ['CharacterBody2D', 'RigidBody2D', 'StaticBody2D', 'Area2D', 'CollisionShape2D', 'CharacterBody3D', 'RigidBody3D', 'StaticBody3D', 'Area3D', 'CollisionShape3D'],
          description: 'Physics node type. Defaults to StaticBody2D.',
        },
        nodeName: { type: 'string', description: 'Name for the new physics node' },
        shapeType: { type: 'string', enum: ['RectangleShape2D', 'CircleShape2D', 'CapsuleShape2D', 'BoxShape3D', 'SphereShape3D', 'CapsuleShape3D'], description: 'Shape resource for CollisionShape nodes' },
        properties: { type: 'object', description: 'Node or shape properties, including collision_layer and collision_mask' },
      },
      required: ['projectPath', 'scenePath'],
    },
  },
  {
    name: 'navigation',
    description: 'Create and list NavigationRegion and NavigationAgent nodes',
    inputSchema: {
      type: 'object',
      properties: {
        projectPath: { type: 'string', description: 'Path to the Godot project directory' },
        scenePath: { type: 'string', description: 'Project-relative scene path' },
        action: { type: 'string', enum: ['create', 'list', 'set_polygon'], description: 'Navigation action. Defaults to list.' },
        parentNodePath: { type: 'string', description: 'Parent node path for create. Defaults to root.' },
        nodeType: { type: 'string', enum: ['NavigationRegion2D', 'NavigationAgent2D', 'NavigationRegion3D', 'NavigationAgent3D', 'NavigationObstacle2D', 'NavigationObstacle3D'], description: 'Navigation node type. Defaults to NavigationRegion2D.' },
        nodeName: { type: 'string', description: 'Name for the new navigation node' },
        nodePath: { type: 'string', description: 'Navigation node path for set_polygon' },
        points: { type: 'array', items: { type: 'object' }, description: '2D points for NavigationRegion2D polygon vertices' },
        properties: { type: 'object', description: 'Node properties such as radius, path_desired_distance, or debug_enabled' },
      },
      required: ['projectPath', 'scenePath'],
    },
  },
  {
    name: 'audio',
    description: 'Create and list AudioStreamPlayer nodes with basic playback configuration',
    inputSchema: {
      type: 'object',
      properties: {
        projectPath: { type: 'string', description: 'Path to the Godot project directory' },
        scenePath: { type: 'string', description: 'Project-relative scene path' },
        action: { type: 'string', enum: ['create', 'list', 'list_buses'], description: 'Audio action. Defaults to list.' },
        parentNodePath: { type: 'string', description: 'Parent node path for create. Defaults to root.' },
        nodeType: { type: 'string', enum: ['AudioStreamPlayer', 'AudioStreamPlayer2D', 'AudioStreamPlayer3D'], description: 'Audio node type. Defaults to AudioStreamPlayer.' },
        nodeName: { type: 'string', description: 'Name for the new audio node' },
        streamPath: { type: 'string', description: 'Optional project-relative audio stream path' },
        bus: { type: 'string', description: 'Audio bus name. Defaults to Master.' },
        volumeDb: { type: 'number', description: 'Volume in decibels' },
        autoplay: { type: 'boolean', description: 'Whether the player starts automatically' },
        properties: { type: 'object', description: 'Additional audio player properties' },
      },
      required: ['projectPath', 'scenePath'],
    },
  },
];
