export type CompatibilityToolRoute = {
  toolName: string;
  canonicalTool?: string;
  fixedArgs?: Record<string, unknown>;
  fieldMap?: Record<string, string>;
  unsupportedReason?: string;
  runMode?: string;
  riskLevel?: string;
};

export const DIRECT_COMPATIBILITY_ALIASES: Record<string, string> = {
  get_project_settings: 'project_get_settings',
  set_project_setting: 'project_set_setting',
  open_scene: 'scene_open',
  play_scene: 'run_project',
  stop_scene: 'stop_project',
  duplicate_node: 'node_duplicate',
  move_node: 'node_move',
  update_property: 'node_set_property',
  list_scripts: 'get_script_index',
  read_script: 'read_script_file',
  create_script: 'script_create',
  attach_script: 'script_attach',
  validate_script: 'check_gdscript_syntax',
  list_export_presets: 'get_export_presets',
  read_resource: 'resource_load',
  create_resource: 'resource_create',
  clear_output: 'clear_debug_output',
  get_output_log: 'get_debug_output',
  project_path_to_uid: 'get_uid',
};

const ROUTED_COMPATIBILITY_TOOLS: CompatibilityToolRoute[] = [
  { toolName: 'connect_signal', canonicalTool: 'signal', fixedArgs: { action: 'connect' } },
  { toolName: 'disconnect_signal', canonicalTool: 'signal', fixedArgs: { action: 'disconnect' } },
  { toolName: 'get_input_actions', canonicalTool: 'project_input_action', fixedArgs: { action: 'list' } },
  { toolName: 'set_input_action', canonicalTool: 'project_input_action', fixedArgs: { action: 'update' } },
  { toolName: 'list_animations', canonicalTool: 'animation', fixedArgs: { action: 'list' } },
  { toolName: 'create_animation', canonicalTool: 'animation', fixedArgs: { action: 'create' } },
  { toolName: 'tilemap_set_cell', canonicalTool: 'tilemap', fixedArgs: { action: 'set_cell' } },
  { toolName: 'tilemap_fill_rect', canonicalTool: 'tilemap', fixedArgs: { action: 'fill_rect' } },
  { toolName: 'create_shader', canonicalTool: 'shader', fixedArgs: { action: 'create' } },
  { toolName: 'read_shader', canonicalTool: 'shader', fixedArgs: { action: 'read' } },
  { toolName: 'assign_shader_material', canonicalTool: 'material', fixedArgs: { action: 'apply' } },
  { toolName: 'set_shader_param', canonicalTool: 'shader', fixedArgs: { action: 'set_parameters' }, fieldMap: { parameter: 'parameters' } },
  { toolName: 'get_shader_params', canonicalTool: 'shader', fixedArgs: { action: 'inspect' } },
  { toolName: 'setup_lighting', canonicalTool: 'lighting', fixedArgs: { action: 'create' } },
  { toolName: 'create_particles', canonicalTool: 'particle', fixedArgs: { action: 'create' } },
  { toolName: 'setup_navigation_region', canonicalTool: 'navigation', fixedArgs: { action: 'create', nodeType: 'NavigationRegion2D' } },
  { toolName: 'setup_navigation_agent', canonicalTool: 'navigation', fixedArgs: { action: 'create', nodeType: 'NavigationAgent2D' } },
  { toolName: 'add_audio_player', canonicalTool: 'audio', fixedArgs: { action: 'create' } },
  { toolName: 'get_audio_bus_layout', canonicalTool: 'audio', fixedArgs: { action: 'list_buses' } },
  { toolName: 'create_animation_tree', canonicalTool: 'animation_state_machine', fixedArgs: { action: 'create' } },
  { toolName: 'get_filesystem_tree', canonicalTool: 'filesystem_list', fixedArgs: { directory: '' } },
  { toolName: 'get_scene_file_content', canonicalTool: 'filesystem_read', fieldMap: { scenePath: 'filePath' } },
  { toolName: 'delete_scene', canonicalTool: 'filesystem_delete', fieldMap: { scenePath: 'targetPath' }, fixedArgs: { confirm: true } },
  { toolName: 'add_resource', canonicalTool: 'resource_create', fixedArgs: { resourceType: 'Resource' } },
  { toolName: 'edit_script', canonicalTool: 'script_write' },
  { toolName: 'get_signals', canonicalTool: 'signal', fixedArgs: { action: 'list' } },
  { toolName: 'add_animation_track', canonicalTool: 'animation', fixedArgs: { action: 'add_track' } },
  { toolName: 'set_animation_keyframe', canonicalTool: 'animation', fixedArgs: { action: 'set_keyframe' } },
  { toolName: 'get_animation_info', canonicalTool: 'animation', fixedArgs: { action: 'get_info' } },
  { toolName: 'remove_animation', canonicalTool: 'animation', fixedArgs: { action: 'remove' } },
  { toolName: 'tilemap_get_info', canonicalTool: 'tilemap', fixedArgs: { action: 'list' } },
  { toolName: 'create_theme', canonicalTool: 'ui', fixedArgs: { action: 'create_theme', nodeType: 'Control', nodeName: 'ThemeRoot' } },
  { toolName: 'find_nodes_by_type', canonicalTool: 'node_find' },
  { toolName: 'get_export_info', canonicalTool: 'export_matrix' },
  { toolName: 'edit_resource', canonicalTool: 'resource_save' },
  { toolName: 'setup_physics_body', canonicalTool: 'physics', fixedArgs: { action: 'create' } },
  { toolName: 'setup_collision', canonicalTool: 'physics', fixedArgs: { action: 'create_shape_resource' } },
  { toolName: 'set_physics_layers', canonicalTool: 'physics', fixedArgs: { action: 'set_layers' } },
  { toolName: 'get_collision_info', canonicalTool: 'physics', fixedArgs: { action: 'get_collision_info' } },
  { toolName: 'setup_environment', canonicalTool: 'lighting', fixedArgs: { action: 'create', nodeType: 'WorldEnvironment' } },
  { toolName: 'set_material_3d', canonicalTool: 'material', fixedArgs: { action: 'apply' } },
  { toolName: 'bake_navigation_mesh', canonicalTool: 'navigation', fixedArgs: { action: 'bake_navigation_mesh' } },
  { toolName: 'get_navigation_info', canonicalTool: 'navigation', fixedArgs: { action: 'list' } },
  { toolName: 'get_audio_info', canonicalTool: 'audio', fixedArgs: { action: 'list' } },
  { toolName: 'find_unused_resources', canonicalTool: 'resource_dependency_graph' },
  { toolName: 'get_project_statistics', canonicalTool: 'get_project_info' },
];

const unsupported = (toolName: string, unsupportedReason: string, runMode = 'compatibility_unsupported'): CompatibilityToolRoute => ({
  toolName,
  unsupportedReason,
  runMode,
  riskLevel: toolName.includes('set') || toolName.includes('add') || toolName.includes('remove') || toolName.includes('execute') || toolName.includes('simulate') || toolName.includes('click') || toolName.includes('move') ? 'write' : 'read',
});

const UNSUPPORTED_COMPATIBILITY_TOOLS: CompatibilityToolRoute[] = [
  unsupported('search_files', 'Text search is not yet exposed as a project-local MCP tool. Use filesystem_list plus filesystem_read, or run search outside the MCP server.'),
  unsupported('uid_to_project_path', 'Godot UID reverse lookup requires an editor resource UID index that is not exposed by this release.'),
  unsupported('add_scene_instance', 'PackedScene instancing needs a scene graph edit operation that is not implemented yet.'),
  unsupported('set_anchor_preset', 'Control anchor preset editing is not implemented as a structured scene operation yet.'),
  unsupported('get_node_groups', 'Group listing is available through the group tool with action=list and a concrete nodePath.'),
  unsupported('set_node_groups', 'Batch group replacement is not implemented; use the group tool add/remove actions for individual changes.'),
  unsupported('find_nodes_in_group', 'Group-wide scene search is not implemented yet.'),
  unsupported('get_open_scripts', 'Open script tabs require live editor bridge state not exposed by this release.', 'editor_bridge_optional'),
  unsupported('search_in_files', 'Project-wide text search is not implemented as an MCP tool yet.'),
  unsupported('get_editor_errors', 'Editor diagnostics require live editor bridge integration beyond the current file-command bridge.', 'editor_bridge_optional'),
  unsupported('get_editor_screenshot', 'Editor screenshot capture requires live editor image transport that is not implemented yet.', 'editor_bridge_optional'),
  unsupported('get_game_screenshot', 'Running game screenshot capture requires runtime image transport that is not implemented yet.', 'runtime_bridge_required'),
  unsupported('execute_editor_script', 'Executing arbitrary editor scripts is intentionally not exposed without a stronger permission and sandbox model.', 'editor_bridge_optional'),
  unsupported('reload_plugin', 'Plugin reload control requires live editor command support that is not implemented yet.', 'editor_bridge_optional'),
  unsupported('reload_project', 'Project reload control requires live editor command support that is not implemented yet.', 'editor_bridge_optional'),
  unsupported('simulate_key', 'Input simulation requires a running-game automation bridge that is not implemented yet.', 'runtime_bridge_required'),
  unsupported('simulate_mouse_click', 'Input simulation requires a running-game automation bridge that is not implemented yet.', 'runtime_bridge_required'),
  unsupported('simulate_mouse_move', 'Input simulation requires a running-game automation bridge that is not implemented yet.', 'runtime_bridge_required'),
  unsupported('simulate_action', 'Input simulation requires a running-game automation bridge that is not implemented yet.', 'runtime_bridge_required'),
  unsupported('simulate_sequence', 'Input simulation requires a running-game automation bridge that is not implemented yet.', 'runtime_bridge_required'),
  unsupported('get_game_scene_tree', 'Runtime scene tree inspection requires a running-game automation bridge that is not implemented yet.', 'runtime_bridge_required'),
  unsupported('get_game_node_properties', 'Runtime node inspection requires a running-game automation bridge that is not implemented yet.', 'runtime_bridge_required'),
  unsupported('set_game_node_property', 'Runtime node mutation requires a running-game automation bridge that is not implemented yet.', 'runtime_bridge_required'),
  unsupported('execute_game_script', 'Runtime script execution requires a running-game automation bridge and permission model that are not implemented yet.', 'runtime_bridge_required'),
  unsupported('capture_frames', 'Frame capture requires runtime image transport that is not implemented yet.', 'runtime_bridge_required'),
  unsupported('monitor_properties', 'Property monitoring requires runtime bridge subscriptions that are not implemented yet.', 'runtime_bridge_required'),
  unsupported('start_recording', 'Input/session recording requires a runtime automation bridge that is not implemented yet.', 'runtime_bridge_required'),
  unsupported('stop_recording', 'Input/session recording requires a runtime automation bridge that is not implemented yet.', 'runtime_bridge_required'),
  unsupported('replay_recording', 'Input/session replay requires a runtime automation bridge that is not implemented yet.', 'runtime_bridge_required'),
  unsupported('find_nodes_by_script', 'Script-backed scene search is not implemented yet.'),
  unsupported('get_autoload', 'Autoload inspection is available in get_project_info, but this exact focused tool is not implemented yet.'),
  unsupported('batch_get_properties', 'Batch property reads are not implemented yet; use get_node_properties for individual nodes.'),
  unsupported('find_ui_elements', 'UI semantic search is not implemented yet.'),
  unsupported('click_button_by_text', 'Runtime UI clicking requires a running-game automation bridge that is not implemented yet.', 'runtime_bridge_required'),
  unsupported('wait_for_node', 'Runtime wait conditions require a running-game automation bridge that is not implemented yet.', 'runtime_bridge_required'),
  unsupported('find_nearby_nodes', 'Spatial proximity search is not implemented yet.'),
  unsupported('navigate_to', 'Runtime navigation commands require a running-game automation bridge that is not implemented yet.', 'runtime_bridge_required'),
  unsupported('move_to', 'Runtime movement commands require a running-game automation bridge that is not implemented yet.', 'runtime_bridge_required'),
  unsupported('tilemap_get_cell', 'TileMap cell reads are not implemented yet.'),
  unsupported('tilemap_clear', 'TileMap clear is not implemented yet.'),
  unsupported('tilemap_get_used_cells', 'TileMap used-cell inspection is not implemented yet.'),
  unsupported('set_theme_color', 'Incremental Theme mutation is not implemented yet; use ui action=create_theme with colors.'),
  unsupported('set_theme_constant', 'Incremental Theme mutation is not implemented yet; use ui action=create_theme with constants.'),
  unsupported('set_theme_font_size', 'Incremental Theme mutation is not implemented yet; use ui action=create_theme with fontSizes.'),
  unsupported('set_theme_stylebox', 'Incremental Theme mutation is not implemented yet; use ui action=create_theme with styleboxes.'),
  unsupported('get_theme_info', 'Theme inspection is not implemented yet.'),
  unsupported('get_performance_monitors', 'Performance monitor reads require live runtime/editor sampling that is not implemented yet.', 'runtime_bridge_required'),
  unsupported('get_editor_performance', 'Editor performance reads require live editor sampling that is not implemented yet.', 'editor_bridge_optional'),
  unsupported('find_signal_connections', 'Signal connection search is not implemented yet.'),
  unsupported('batch_set_property', 'Batch scene property mutation is not implemented yet.'),
  unsupported('find_node_references', 'Node reference analysis is not implemented yet.'),
  unsupported('get_scene_dependencies', 'Scene-focused dependency analysis is not implemented yet; use resource_dependency_graph for project-wide dependencies.'),
  unsupported('cross_scene_set_property', 'Cross-scene mutation is not implemented yet.'),
  unsupported('find_script_references', 'Project-wide script reference search is not implemented yet.'),
  unsupported('detect_circular_dependencies', 'Circular dependency detection is not implemented yet.'),
  unsupported('edit_shader', 'Incremental shader editing is not implemented yet; use shader action=create to overwrite shader content.'),
  unsupported('get_resource_preview', 'Resource preview generation requires editor/runtime rendering that is not implemented yet.'),
  unsupported('add_autoload', 'Autoload mutation is not implemented yet.'),
  unsupported('remove_autoload', 'Autoload mutation is not implemented yet.'),
  unsupported('get_physics_layers', 'Named physics layer reads are not implemented yet.'),
  unsupported('add_raycast', 'RayCast node helper is not implemented yet; use add_node with a RayCast node type.'),
  unsupported('add_mesh_instance', 'MeshInstance helper is not implemented yet; use add_node with MeshInstance3D.'),
  unsupported('setup_camera_3d', 'Camera3D helper is not implemented yet; use add_node with Camera3D.'),
  unsupported('add_gridmap', 'GridMap helper is not implemented yet; use add_node with GridMap.'),
  unsupported('set_particle_material', 'Particle material mutation is not implemented yet.'),
  unsupported('set_particle_color_gradient', 'Particle color gradient mutation is not implemented yet.'),
  unsupported('apply_particle_preset', 'Particle presets are not implemented yet.'),
  unsupported('get_particle_info', 'Particle inspection is not implemented yet.'),
  unsupported('set_navigation_layers', 'Navigation layer mutation is not implemented yet.'),
  unsupported('add_audio_bus', 'Audio bus layout mutation is not implemented yet.'),
  unsupported('add_audio_bus_effect', 'Audio bus effect mutation is not implemented yet.'),
  unsupported('set_audio_bus', 'Audio bus assignment helper is not implemented yet; use audio action=create for new players.'),
  unsupported('get_animation_tree_structure', 'AnimationTree structure inspection is not implemented yet.'),
  unsupported('set_tree_parameter', 'AnimationTree parameter mutation is not implemented yet.'),
  unsupported('add_state_machine_state', 'State machine graph mutation is not implemented yet.'),
  unsupported('remove_state_machine_state', 'State machine graph mutation is not implemented yet.'),
  unsupported('add_state_machine_transition', 'State machine graph mutation is not implemented yet.'),
  unsupported('remove_state_machine_transition', 'State machine graph mutation is not implemented yet.'),
  unsupported('set_blend_tree_node', 'Blend tree mutation is not implemented yet.'),
  unsupported('analyze_scene_complexity', 'Scene complexity analysis is not implemented yet.'),
  unsupported('analyze_signal_flow', 'Signal flow analysis is not implemented yet.'),
  unsupported('run_test_scenario', 'Runtime QA scenarios require a running-game automation bridge that is not implemented yet.', 'runtime_bridge_required'),
  unsupported('assert_node_state', 'Runtime QA assertions require a running-game automation bridge that is not implemented yet.', 'runtime_bridge_required'),
  unsupported('assert_screen_text', 'Screen text assertions require runtime screenshot/OCR transport that is not implemented yet.', 'runtime_bridge_required'),
  unsupported('compare_screenshots', 'Screenshot comparison requires runtime image capture that is not implemented yet.', 'runtime_bridge_required'),
  unsupported('run_stress_test', 'Stress testing requires runtime automation orchestration that is not implemented yet.', 'runtime_bridge_required'),
  unsupported('get_test_report', 'QA report storage is not implemented yet.'),
];

export const COMPATIBILITY_TOOL_ROUTES: Record<string, CompatibilityToolRoute> = Object.fromEntries(
  [...ROUTED_COMPATIBILITY_TOOLS, ...UNSUPPORTED_COMPATIBILITY_TOOLS].map((route) => [route.toolName, route])
);

export const REQUIRED_COMPATIBILITY_TOOL_NAMES_17 = [
  ...Object.keys(DIRECT_COMPATIBILITY_ALIASES),
  ...Object.keys(COMPATIBILITY_TOOL_ROUTES),
];
